//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawShip.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawShip.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model DrawShip.Viewer.DrawingViewModel
        ///&lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;@Model.DrawingTitle&lt;/title&gt;
        ///
        ///	&lt;style&gt;
        ///		body {
        ///			padding: 0px;
        ///			margin: 0px;
        ///		}
        ///
        ///        .drawing-title-position {
        ///			margin: 0px;
        ///			padding: 0px;
        ///			position: absolute;
        ///		    left: 0px;
        ///		    right: 0px;
        ///		    top: 1px;
        ///		    height: 28px;
        ///            z-index: 1;
        ///		}
        ///
        ///        .drawing-title-style {
        ///			background: #EEEEEE;
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Drawing {
            get {
                return ResourceManager.GetString("Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model DrawShip.Viewer.IndexViewModel
        ///&lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;DrawShip detail&lt;/title&gt;
        ///
        ///	&lt;style&gt;
        ///		body {
        ///			padding: 0px;
        ///			margin: 0px;
        ///			font-family: Tahoma;
        ///			font-size: 14px;
        ///		}
        ///
        ///		.drawing-title {
        ///			font-size: 14px;
        ///			margin: 0px;
        ///			padding: 0px;
        ///			background: #ffff88;
        ///			padding-bottom: 2px;
        ///			margin-bottom: 2px;
        ///			border-bottom: 1px solid #888800;
        ///			font-weight: normal;
        ///			posit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model DrawShip.Viewer.NotFoundViewModel
        ///&lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;DrawShip - diagram not found&lt;/title&gt;
        ///
        ///    &lt;style&gt;
        ///        body {
        ///            padding: 0px;
        ///            margin: 0px;
        ///            font-family: Tahoma;
        ///            font-size: 14px;
        ///        }
        ///
        ///        .drawing-title {
        ///            font-size: 14px;
        ///            margin: 0px;
        ///            padding: 0px;
        ///            background: #ffff88;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PreviewHtml {
            get {
                object obj = ResourceManager.GetObject("PreviewHtml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PreviewImage {
            get {
                object obj = ResourceManager.GetObject("PreviewImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrintDrawing {
            get {
                object obj = ResourceManager.GetObject("PrintDrawing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon tray_icon {
            get {
                object obj = ResourceManager.GetObject("tray_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
